### PR TITLE
Add a first pass at an api implementation

### PR DESCRIPTION
**Pull request by thekevinscott**
In reference to https://github.com/L4GG/timeline/issues/45

This is a first pass at an API. Sounds like we may want to pause on this which is fine.

The big things here:

* It's moving the `events` directory to a new folder, `content`. This obviously won't work with the current webpack build process, but I'm not sure the best way to tackle this.
* From there, the API exposes a few routes, like `/api/years`, `/api/years/1984`, and `/api/years/1984/trump-declares-nuclear-ambitions` that map directly to the file structure of events
* The events route exposes an object with the directory's files as the keys, and each file's contents as the values.

### CODE REVIEW

**Comment by thekevinscott** [comment]
So I think one big change would be to *not* copy the events folder to `/content` (per @jlegrone's comment on the issue) and have webpack output an `events.bundle.js` that could be consumable via the API. Looks like webpack is wrapping the directory contents in non-Node-friendly ways so that might take a bit of work, I'm not totally familiar with the current config.

**Comment by jlegrone** [comment]
@thekevinscott mind splitting this into two commits (one to move the events directory) and force pushing so that the important changes are easier to inspect?

**Comment by thekevinscott** [comment]
@jlegrone I can definitely do that, although pursuant to the suggestion from @anseljh on https://github.com/L4GG/timeline/issues/45 - what if I do a first PR, that just takes the existing `src/events` folder and spits out an `events.bundle.js` file (a JSON object containing all the events), and then this PR to consume that?

There's a lot of directory/file reading functions in this PR that could be removed if we're just dealing with a single JSON file.

**Comment by anseljh** [comment]
Sorry if I'm being dense, but what is the purpose of this API?

**Comment by jlegrone** [comment]
@thekevinscott I'm going to table this for now in favor of just building a single events.json object.  I don't want to introduce complexity before it's needed.  Let's also avoid changing the events directory location, as that's a whopping diff and git blame also becomes a little less easy to use. 😉

**Pull request closed without merging**
